// This is to suppress false warnings generated by a bug in IntelliJ
@file:Suppress("DSL_SCOPE_VIOLATION", "MISSING_DEPENDENCY_CLASS", "FUNCTION_CALL_EXPECTED", "PropertyName")

plugins {
    id("maven-publish")

    alias(libs.plugins.kotlin)
//    id("fabric-loom") version "1.3.9"
    id("org.quiltmc.loom") version "(1.+)"
}

group = project.properties["maven_group"]!!
version = project.properties["mod_version"]!!
base.archivesName.set(project.properties["archives_base_name"] as String)

repositories {
//    maven {
//        name ="Quilt"
//        url = uri("https://maven.quiltmc.org/repository/release")
//    }
}

dependencies {
    minecraft("com.mojang:minecraft:1.20.1")


//            mappings variantOf(libs.quilt.mappings) { classifier 'intermediary-v2' }
    mappings("net.fabricmc:yarn:1.20.1+build.10:v2")
//    modImplementation(libs.quilt.loader)
}



tasks {
    processResources {
        inputs.property("version", project.version)
        filteringCharset = "UTF-8"

        filesMatching("quilt.mod.json") {
            expand(mapOf("version" to project.version))
        }
    }

    val targetJavaVersion = 17

    withType<JavaCompile> {
        options.encoding = "UTF-8"
        options.release.set(targetJavaVersion)
    }

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(JavaVersion.toVersion(targetJavaVersion).toString()))
        withSourcesJar()
    }
}